// tailwind.config.ts
import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#2f1500",
        "on-surface-variant": "#444748",
        "on-primary-fixed-variant": "#474646",
        "secondary-fixed": "#8df9a8",
        "surface-variant": "#d3e4fe",
        "on-surface": "#0b1c30",
        "error-container": "#ffdad6",
        "secondary": "#006d35",
        "outline-variant": "#c4c7c7",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#00210c",
        "on-error": "#ffffff",
        "primary-fixed": "#e5e2e1",
        "primary-fixed-dim": "#c8c6c5",
        "on-primary": "#ffffff",
        "surface": "#f8f9ff",
        "on-tertiary-container": "#c76c00",
        "background": "#f8f9ff",
        "primary-container": "#1c1b1b",
        "surface-container": "#e5eeff",
        "on-secondary-container": "#007439",
        "inverse-primary": "#c8c6c5",
        "tertiary-fixed-dim": "#ffb77d",
        "outline": "#747878",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#5f5e5e",
        "on-tertiary-fixed-variant": "#6e3900",
        "on-error-container": "#93000a",
        "surface-container-high": "#dce9ff",
        "inverse-surface": "#213145",
        "inverse-on-surface": "#eaf1ff",
        "on-primary-container": "#858383",
        "secondary-container": "#8df9a8",
        "surface-bright": "#f8f9ff",
        "on-tertiary-fixed": "#2f1500",
        "tertiary": "#000000",
        "secondary-fixed-dim": "#71dc8e",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "surface-container-highest": "#d3e4fe",
        "on-primary-fixed": "#1c1b1b",
        "primary": "#000000",
        "surface-dim": "#cbdbf5",
        "on-secondary-fixed-variant": "#005226",
        "tertiary-fixed": "#ffdcc3",
        "surface-container-low": "#eff4ff",
        "on-background": "#0b1c30"
      },
      fontFamily: {
        headline: ["var(--font-manrope)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        label: ["var(--font-inter)", "sans-serif"],
      },
    },
  },
  plugins: [],
};
export default config;